local exclude_patterns = {
	"node_modules",
	"package_lock.json",
	"assets/",
	"%.tscn",
	"%.gd.uid",
	".godot/",
	"env/",
	".mypy_cache",
	".next/",
	".venv",
	"__pycache__",
	".git/",
	"target/",
	"docs/",
	"vendor/*",
	"%.lock",
	"__pycache__/*",
	"%.sqlite3",
	"%.ipynb",
	"node_modules/*",
	"%.webp",
	".github/",
	".idea/",
	".settings/",
	".vscode/",
	"__pycache__/",
	"node_modules/",
	"%.pdb",
	"%.dll",
	"%.class",
	"%.exe",
	"%.cache",
	"%.ico",
	"%.pdf",
	"%.dylib",
	"%.jar",
	"%.docx",
	"%.met",
	"smalljre_*/*",
	".vale/",
	"%.burp",
	"%.mp4",
	"%.mkv",
	"%.rar",
	"%.zip",
	"%.7z",
	"%.tar",
	"%.bz2",
	"%.epub",
	"%.flac",
	"%.tar.gz",
	"%__virtual.cs$",
	"pnpm%-lock%.yaml",
}

return {
	enabled = true,
	sources = {
		files = { exclude = exclude_patterns },
		grep = { exclude = exclude_patterns },
	},
	win = {
		input = {
			keys = {
				["<C-l>"] = { "edit_vsplit", mode = { "i", "n" } },
				["<C-j>"] = { "edit_split", mode = { "i", "n" } },
				["<C-e>"] = "close",
				["q"] = { "close", mode = "n" },
				["<C-d>"] = { "preview_scroll_down", mode = { "i", "n" } },
				["<C-u>"] = { "preview_scroll_up", mode = { "i", "n" } },
				["<leader>pf"] = { "switch_files", mode = { "i", "n" } },
				["<leader>ps"] = { "switch_grep", mode = { "i", "n" } },
				["<Tab>"] = { "list_down", mode = { "i", "n" } },
				["<S-Tab>"] = { "list_up", mode = { "i", "n" } },
			},
		},
		list = {
			wo = { winhighlight = "Normal:Normal,NormalNC:Normal" },
		},
		preview = {
			wo = { winhighlight = "Normal:Normal,NormalNC:Normal" },
		},
	},
	layout = {
		layout = {
			box = "horizontal",
			width = 0,
			height = 0,
			{
				box = "vertical",
				width = 0.4,
				border = "rounded",
				title = " {title} {live} {flags}",
				title_pos = "center",
				{ win = "input", height = 1, border = "bottom" },
				{ win = "list", border = "none" },
			},
			{ win = "preview", title = " {preview} ", title_pos = "center", border = "rounded" },
		},
	},
	formatters = {
		file = {
			filename_first = true,
		},
	},
}
