#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="GohuFont Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=10 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=45
  color=$TRANSPARENT
  border_width=2
  border_color=$TRANSPARENT
  corner_radius=15
  shadow=off
  position=top
  sticky=on
  padding_right=0
  padding_left=0
  y_offset=10
  margin=10
  topmost=window
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  background.height=26
  background.corner_radius=9
  background.border_width=1
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$CYAN
  popup.background.color=$DARKER_BLACK
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

#Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/yabai.sh"
# source "$ITEM_DIR/front_app.sh"

# # Center
# source "$ITEM_DIR/spotify.sh"

#  Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
# source "$ITEM_DIR/cpu.sh"

ITEMS=$(sketchybar --query bar | jq -r '.items | .[]')
LEFT_ITEMS=()
RIGHT_ITEMS=()

for item in $ITEMS
do
  POS=$(sketchybar --query ${item} | jq -r '.geometry.position')
  if [ "$POS" = "left" ]; then
    LEFT_ITEMS+=(${item})
  elif [ "$POS" = "right" ]; then
    RIGHT_ITEMS+=(${item})
  fi
done

bracket=(
  background.color=$(get_color ONE_BG 40)
  background.height=40
  background.corner_radius=20
  background.border_color=$(get_color RED)
  blur_radius=5
)

sketchybar --add bracket left_items ${LEFT_ITEMS[@]} \
           --set left_items "${bracket[@]}" 

sketchybar --add bracket right_items ${RIGHT_ITEMS[@]} \
           --set right_items "${bracket[@]}" 

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
