#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="Inconsolata Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=10 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER > /dev/null 2>&1 &


# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/front_app.sh"

# Center
source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/wifi.sh"
# source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"
# Setting up the general bar appearance of the bar

bar=(
  # border_color=$BAR_BORDER_COLOR
  height=35
  color=$TRANSPARENT
  border_width=0
  corner_radius=15
  shadow=off
  position=top
  sticky=on
  y_offset=0
  margin=10
  topmost=window
  padding_right=0
  padding_left=0
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  label.font="$FONT:Semibold:13.0"
  label.font.size=13
  label.color=$LABEL_COLOR
  background.height=26
  background.corner_radius=9
  background.border_width=2
)

sketchybar --default "${defaults[@]}"

ITEMS=$(sketchybar --query bar | jq -r '.items | .[]')
LEFT_ITEMS=()
RIGHT_ITEMS=()

for item in $ITEMS
do
  POS=$(sketchybar --query ${item} | jq -r '.geometry.position')
  if [ "$POS" = "left" ]; then
    LEFT_ITEMS+=(${item})
  elif [ "$POS" = "right" ]; then
    RIGHT_ITEMS+=(${item})
  fi
done

bracket=(
  background.color=0x992d2b38
  background.height=30
  background.border_width=2
  background.corner_radius=20
  background.border_color=0xffa3d6df
  blur_radius=5
)

sketchybar --add bracket left_items ${LEFT_ITEMS[@]} \
           --set left_items "${bracket[@]}" 

sketchybar --add bracket right_items ${RIGHT_ITEMS[@]} \
           --set right_items "${bracket[@]}" 


# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
