#!/bin/sh
source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
POPUP_CLICK_SCRIPT="sketchybar --set \$NAME popup.drawing=toggle"
ACTIVE_SPACE=$(yabai -m query --spaces --space | jq '.index')
SPACE_ICONS=("$GHOST" "$GHOST" "$GHOST" "$GHOST" "$GHOST" "$GHOST" "$GHOST" "$GHOST")

bar=(
  height=30
  # margin=0
  corner_radius=10
  position=top
  color=$TRANSPARENT
  border_color=$WHITE
  y_offset=4
  sticky=off
)

sketchybar --bar "${bar[@]}"

defaults=(
  updates=when_shown
  icon.drawing=on
  icon.font="Monaspace Neon:Regular:12.0"
  icon.color=$WHITE
  label.font="Monaspace Neon:Regular:12.0"
  label.drawing=on
  label.color=$WHITE
  popup.background.color=$STATUS
  popup.background.corner_radius=10
  popup.background.border_width=1
  popup.background.border_color=$WHITE
  popup.blur_radius=100
)

sketchybar --default "${defaults[@]}"

time=(
  update_freq=1
  script="$PLUGIN_DIR/time.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  label.font="Monaspace Neon:Bold:12.0"
  label.padding_left=20
  label.padding_right=15
  background.corner_radius=10
  background.color=$TEMPUS
  background.height=19
  background.padding_left=-10
  background.padding_right=3
  background.border_color=$WHITE
)

sketchybar --add item time right \
  --set time "${time[@]}" \
  --subscribe time system_woke

date=(
  update_freq=30
  script="$PLUGIN_DIR/date.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  label.padding_left=15
  background.color=$TEMPUS
  background.height=19
  background.corner_radius=10
)

sketchybar --add item date right \
  --set date "${date[@]}" \
  --subscribe date system_woke

wifi=(
  script="$PLUGIN_DIR/wifi.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  label.padding_right=15
  update_freq=60
)

rm -f /tmp/sketchybar_speed
rm -f /tmp/sketchybar_wifi
sketchybar --add item wifi right \
  --set wifi "${wifi[@]}" \
  --subscribe wifi system_woke

battery=(
  script="$PLUGIN_DIR/battery.sh"
  update_freq=120
  updates=on
  click_script="$POPUP_CLICK_SCRIPT"
  label.padding_left=15
)

sketchybar --add item battery right \
  --set battery "${battery[@]}" \
  --subscribe battery power_source_change system_woke

volume=(
  script="$PLUGIN_DIR/volume.sh"
  updates=on
  label.drawing=off
  icon.drawing=off
  slider.highlight_color=$WHITE
  slider.background.height=5
  slider.background.corner_radius=3
  slider.background.color=$GREY
  slider.knob=$DOT
  slider.knob.drawing=off
  slider.padding_left=15
  slider.padding_right=15
  label.padding_right=10
  label.padding_left=10
  background.color=$STATUS
  background.height=10
  background.corner_radius=10
  background.border_width=1
  background.border_color=$WHITE
  background.padding_right=7
)

sketchybar --add slider volume right \
  --set volume "${volume[@]}" \
  --subscribe volume volume_change mouse.clicked mouse.entered mouse.exited

volume_icon=(
  script="$PLUGIN_DIR/volume_icon.sh"
  click_script="$PLUGIN_DIR/volume_click.sh"
  label.padding_right=8
  label.padding_left=20
)

sketchybar --add item volume_icon right \
  --set volume_icon "${volume_icon[@]}"

ram=(
  icon=$RAM
  icon.padding_left=15
  script="$PLUGIN_DIR/ram.sh"
  label.padding_right=15
  label.padding_left=10
  update_freq=60
  background.corner_radius=10
  background.color=$TEMPUS
  background.height=19
  background.padding_left=-6
  background.padding_right=3
  background.border_color=$WHITE
)

sketchybar --add item ram q \
  --set ram "${ram[@]}"

cpu=(
  icon=$CPU
  icon.padding_left=15
  script="$PLUGIN_DIR/cpu.sh"
  label.padding_left=10
  label.padding_right=15
  update_freq=60
)

sketchybar --add item cpu q \
  --set cpu "${cpu[@]}"

apple=(
  script="$PLUGIN_DIR/apple.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  label=$APPLE
  label.padding_right=15
  label.padding_left=15
  background.color=$TEMPUS
  background.height=19
  background.corner_radius=10
  background.padding_left=3
  background.padding_right=3
)

sketchybar --add item apple left \
  --set apple "${apple[@]}"

space=(
  script="$PLUGIN_DIR/spaces.sh"
  label.drawing=off
  icon.padding_left=15
  icon.padding_right=15
  update_freq=1
)

space_bg=(
  background.color=$SPACEBG
  background.height=19
  background.corner_radius=50
)

declare -a spacesArray=()
for i in "${!SPACE_ICONS[@]}"; do
  sid=$(($i + 1))

  if [[ $sid -eq $ACTIVE_SPACE ]]; then
    CURRENT_ICON=$PACMAN
  else
    CURRENT_ICON=${SPACE_ICONS["$i"]}
  fi

  spacesArray+=("space.$sid")

  sketchybar --add space space.$sid left \
    --set space.$sid associated_space=$sid \
    icon="$CURRENT_ICON" \
    click_script="yabai -m space --focus $sid" \
    "${space[@]}"

  if [[ $sid -eq $ACTIVE_SPACE ]]; then
    sketchybar --set space.$sid "${space_bg[@]}"
  fi

done

# current_space=(
#   icon.padding_left=7
#   icon.padding_right=7
#   background.color=$TRANSPARENT
#   background.height=25
#   background.corner_radius=15
#   background.border_color=$WHITE
#   background.border_width=1
#   background.padding_left=10
#   click_script="$POPUP_CLICK_SCRIPT"
# )
#
# sketchybar --add item current_space left \
#   --set current_space "${current_space[@]}"

brackets=(
  background.color=$TRANSPARENT
  background.height=25
  background.corner_radius=10
  background.border_color=$WHITE
  background.border_width=1
)

sketchybar --add bracket status time date wifi battery volume_icon right \
  --set status "${brackets[@]}"

sketchybar --add bracket control apple "${spacesArray[@]}" center \
  --set control "${brackets[@]}"

sketchybar --add bracket utilis ram cpu q \
  --set utilis "${brackets[@]}"

sketchybar --update
