#!/bin/bash
# Yabai Configuration

# Green BSP Settings
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"

# Navigation Shortcuts
yabai -m space --focus prev        # move to previous space
yabai -m space --focus next        # move to next space

# General Configurations
GENERAL=(
  split_type auto
  split_ratio 0.5
  auto_balance on
)

WINDOWS=(
  window_placement second_child
  window_shadow off
  window_opacity on
  active_window_opacity 1.0
  normal_window_opacity 0.4
  window_animation_duration 0.0
  window_origin_display focused
  window_opacity_duration 0.2
)

LAYOUT=(
  layout bsp
  top_padding 5
  bottom_padding 5
  left_padding 5
  right_padding 5
  window_gap 12
)


MOUSE=(
  mouse_modifier ctrl
  mouse_action1 move
  mouse_action2 resize
  mouse_drop_action swap
  mouse_follows_focus on
)

# Apply Configurations
yabai -m config "${GENERAL[@]}"
yabai -m config "${WINDOWS[@]}"
yabai -m config "${LAYOUT[@]}"
yabai -m config "${MOUSE[@]}"

# Rules for Unmanaged Applications
UNMANAGED_APPS=(
  Finder
  System Preferences
  QuickTime Player
  Calendar
  Spotify
  Discord
  Slack
  Microsoft Teams
  Steam
  Zoom.us
  VLC
  App Store
  Notes
  Telegram
  Authy
  Raycast
  Xverse
  Docker Desktop
  Logi Options+
  iStat Menus
  Activity Monitor
  Python
  Godot
  Thunderbird
  Caprine
  Unity
  AI Studio
  MATLAB*
  Cisco*
  Spark
  WhatsApp
  Photo Booth
)

for app in "${UNMANAGED_APPS[@]}"; do
  yabai -m rule --add app="^${app}.*$" manage=off
done

echo "New yabai configuration loaded."

borders inactive_color=0xff97BEDC ctive_color=0xffB1D8F6 width=7.0
yabai -m rule --add app="^tauri-app$" display=^1
