-- require("nightfox").setup({
--   options = {
--     styles = {
--       comments = "italic",
--       keywords = "bold",
--       types = "italic,bold",
--     },
--     transparent = true,
--     dim_active = true,
--   }
-- })
--
-- vim.cmd("colorscheme carbonfox")

